name: Generate READMEs

on:
  push:
    paths:
      - 'solutions/**'

jobs:
  checkForNeededREADMEs:
    runs-on: ubuntu-latest
    outputs:
      foldersNeedingREADMEs: ${{ steps.set_directories.outputs.solutionFolders }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
            
      - name: Check repo for directories without READMEs
        id: set_directories
        run: |
            for directory in $(ls -d solutions/* | cut -d / -f2)
            do
              if ! test -f "solutions/$directory/README.md"
              then
                solutionFolders+=("$directory")
              fi
            done
            echo "solutionFolders=${solutionFolders[@]}" >> $GITHUB_OUTPUT
            

  buildREADMEs:
    needs: [checkForNeededREADMEs]
    if: needs.checkForNeededREADMEs.outputs.foldersNeedingREADMEs != null
    runs-on: ubuntu-latest
    env:
      solutionFolders: ${{needs.checkForNeededREADMEs.outputs.foldersNeedingREADMEs}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v1 
        with:
          node-version: '16.3'
      - name: Install node dependencies
        run: npm install --prefix ./scripts
        
      - name: Echo local folder list
        run: echo ${solutionFolders[@]}
        
      - name: Gather question data json for each valid challenge
        run: |
            for directory in ${solutionFolders[@]}
            do
              node scripts/saveChallengeData.mjs $directory
            done
        
      - name: Block upload of invalid LeetCode challenge solutions
        run: |
            for directory in ${solutionFolders[@]}
            do
              if ! $(jq '.challengesCompleted | has("'$directory'")' scripts/challengeSummary.json)
              then
                rm -r solutions/$directory
              fi
            done
        
      - name: Generate individual solution READMEs
        run: |
            for directory in ${solutionFolders[@]}
            do
              node scripts/buildChallengeReadme.mjs $directory
            done
        
      - name: Update main challenge table
        run: node scripts/buildRepoReadme.mjs
        
      - name: Push changes
        run: |
            if [[ "$(git status --porcelain)" != "" ]]
            then
              git config user.name "GitHub Action"
              git config user.email "action@github.com"
              git add .
              git commit -m "Auto-generate README.md"
              git push
            fi
